### ISSUE TITLE
Response: Json deserialize error: invalid type: boolean `false`, expected i32 at line 1 column 686

### ISSUE THREAD

**Issue by madscientista** [CplSyx/Reddit-to-Lemmy#2]
Getting this while trying to get new content from my community:

<img width="1782" alt="Hmm" src="https://github.com/CplSyx/Reddit-to-Lemmy/assets/32178410/83b10927-e944-4360-a15c-d97b589bd1e0">

Any help would be appreciated

**Comment by CplSyx** [comment]
Sorry for the late response on this. I experienced the same and put a note in the readme - I wasn't able to understand why this would happen as re-running the script would not necessarily reproduce the error. Possibly something in the response that differs but I couldn't find what it was causing the failure.

> (Note: sometimes JSON parse errors are encountered, I am unsure why as they are inconsistent and repeating the same run again will not always reproduce the error. I suggest retrying if this happens.)

**Comment by CplSyx** [comment]
I was able to upload everything by simply retrying the script when it failed as subsequent runs of the same content would not fail. A tricky one but it wasn't worth the time to debug vs just running it again.
